# Generated by Django 5.1.4 on 2024-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_kalk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telefon',
        ),
        migrations.AddField(
            model_name='profile',
            name='waga',
            field=models.FloatField(blank=True, help_text='Waga w kilogramach (np. 69)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wzrost',
            field=models.FloatField(blank=True, help_text='Wzrost w metrach (np. 1.8)', null=True),
        ),
    ]
